In [1]:
from MomentEmu.PolyEmu import PolyEmu
import numpy as np

In [2]:
# print the path to verify the correct module is imported
import MomentEmu
import os
print("Using MomentEmu from:", os.path.dirname(os.path.abspath(MomentEmu.__file__)))


Using MomentEmu from: /Users/zzhang/Workspace/MomentEmu/src/MomentEmu


In [3]:
X_train = np.random.uniform(1, 2, (500, 2))
Y_train1 = (X_train[:, 0]**2 + X_train[:, 1]**2).reshape(-1, 1)
Y_train2 = (X_train[:, 0]**3 + X_train[:, 1]).reshape(-1, 1)
Y_train = np.hstack((Y_train1, Y_train2))
X_train.shape

(500, 2)

In [4]:
emulator = PolyEmu(X_train, Y_train, forward=True, backward=True, standardize_Y_with_std=False)


Generating forward emulator...
Set max_degree_forward to 28. Otherwise, a higher degree will require more samples.
Forward emulator generated with degree 3, RMSE_val of 9.767478496387435e-15.
Performing dimension reduction...
Dimension reduced  from 10 modes to 6 modes.
After the dimension reduction, the RMSE: 4.0408320628897035e-15, AIC: -4959.34886519743, BIC: -28134.664367771893
Generating backward emulator...
Set max_degree_backward to 28. Otherwise, a higher degree will require more samples.
Backward emulator generated with degree 4, RMSE_val of 0.006024727339835413.
Performing dimension reduction...
Dimension reduced  from 15 modes to 15  modes.
After the dimension reduction, the RMSE: 0.006024727339835413, AIC: -736.7824583142824, BIC: -4254.3192595804


In [5]:
emulator.generate_forward_symb_emu()

[-1.62390919776473e-14*x1**3 + 1.00000000000007*x1**2 - 1.0856016260053e-13*x1 + 1.0*x2**2 - 1.33226762955019e-15*x2 + 5.45756119778393e-14,
 1.00000000000026*x1**3 - 1.18660636871937e-12*x1**2 + 1.72839520473644e-12*x1 + 3.69844664945554e-15*x2**2 + 0.999999999999988*x2 - 8.04689648248313e-13]

In [6]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))
print(scaler.mean_)
print(scaler.transform(data))
print(scaler.transform([[2, 2]]))

StandardScaler()
[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[3. 3.]]


In [7]:
scaler.var_

array([0.25, 0.25])